First commit for the chat display. Created items for sent and receive…
carlosjuarez/FinalProject pull request #17
Opened 2018-07-20 06:37 UTC by OnlyAlf

… for the recycler view in the fragment.

2018-07-20 12:00 UTC, itzcoatl90 commented on app/src/main/java/com/batch/mcs/finalproject/ChatUsetInteractionFragment.java
> +public class ChatUsetInteractionFragment extends Fragment {
Can we clean all the code we do not need? This code should not inject to the project code that is going to be removed somewhen....  I will talk about PRs cleanliness today at training... Also, ask Joe how did he create his fragment..... he already did

2018-07-20 12:04 UTC, itzcoatl90 commented on app/src/main/res/layout/fragment_chat_user_interaction.xml
> +        android:layout_width="352dp"
No hardcoding

2018-07-20 12:05 UTC, itzcoatl90 commented on app/src/main/res/layout/recycleview_chat_user_interaction_sent_item.xml
> +                android:layout_width="0dp"
No hardcoding

2018-07-20 12:06 UTC, itzcoatl90 commented on app/src/main/res/values/dimens.xml
> -    <dimen name="title_text_size">12dp</dimen>
Try not to erase something that is already injected in the project

2018-07-20 12:06 UTC, itzcoatl90 commented on app/src/main/res/values/dimens.xml
> -    <dimen name="activity_vertical_margin">8dp</dimen>
Same here

2018-07-20 12:06 UTC, itzcoatl90 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
This is a default String, that you should not use.... if you injected it now, it will be hard to take it out later

2018-07-20 12:07 UTC, itzcoatl90 requested changes
Address comments

2018-07-21 20:39 UTC, itzcoatl90 commented on app/src/main/java/com/batch/mcs/finalproject/ChatUserInteractionFragment.java
> +    private static final String ARG_PARAM1 = "param1";
No... please do not inject default code.... this should never be in the project

2018-07-21 20:40 UTC, itzcoatl90 requested changes
Just 2 comments from this one.... and make sure it will work in every computer

2018-07-23 13:34 UTC, itzcoatl90 commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_7" default="true" project-jdk-name="1.8" project-jdk-type="JavaSDK">
Nop... change this please...

2018-07-23 14:39 UTC, itzcoatl90 requested changes
Update with Development

2018-07-23 14:45 UTC, itzcoatl90 commented on app/src/main/java/com/batch/mcs/finalproject/RecommendedUsersFragment.java
> -package com.batch.mcs.finalproject;
This file is not in Development... that means this PR is not updates

2018-07-23 14:46 UTC, itzcoatl90 commented on app/src/main/java/com/batch/mcs/finalproject/RecommendedUsersFragment.java
> -package com.batch.mcs.finalproject;
updated*

2018-07-23 14:46 UTC, itzcoatl90 requested changes
address

2018-07-24 16:43 UTC, itzcoatl90 commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
Nop... no this files in PRs

2018-07-24 16:43 UTC, itzcoatl90 submitted a review, later dismissed
nop

2018-07-24 20:43 UTC, ecejmsr requested changes
Check typo under string.xml

2018-07-24 20:43 UTC, ecejmsr commented on app/src/main/res/values/strings.xml
> +    <string name="app_name">FInalProject</string>
Redo typo

2018-07-24 21:14 UTC, ecejmsr approved these changes
All looks good.

2018-07-24 21:14 UTC, merged