Alvaro lossada group member display
carlosjuarez/FinalProject pull request #20
Opened 2018-07-20 07:26 UTC by OnlyAlf

2018-07-23 14:43 UTC, itzcoatl90 commented on app/src/main/java/com/batch/mcs/finalproject/GroupMembersFragment.java
> +    // TODO: Rename parameter arguments, choose names that match
Nop.... please do not inject default code...

2018-07-23 14:43 UTC, itzcoatl90 commented on app/src/main/java/com/batch/mcs/finalproject/GroupMembersFragment.java
> +    // TODO: Rename parameter arguments, choose names that match
Check all other fragments

2018-07-23 14:44 UTC, itzcoatl90 commented on app/src/main/res/values/dimens.xml
> -    <dimen name="title_text_size">12dp</dimen>
Are we sure this is not going to break the app?? please do not erase it

2018-07-23 14:44 UTC, itzcoatl90 commented on app/src/main/res/values/dimens.xml
> -    <dimen name="input_margin_start_to_end">8dp</dimen>
Please do not erase it

2018-07-23 14:44 UTC, itzcoatl90 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
do not inject default values

2018-07-23 14:44 UTC, itzcoatl90 requested changes
Address comments

2018-07-24 15:48 UTC, itzcoatl90 commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
Nop...

2018-07-24 15:49 UTC, itzcoatl90 submitted a review, later dismissed
Do not add the files that are not required

2018-07-24 20:46 UTC, ecejmsr approved these changes
Everything looks good.

2018-07-24 23:00 UTC, merged