Fourth Commit. Fixed bugs specified in trello.
carlosjuarez/FinalProject pull request #22
Opened 2018-07-20 08:05 UTC by OnlyAlf

2018-07-20 19:39 UTC, itzcoatl90 requested changes
merge Development to yours and push or rebase please

2018-07-21 20:19 UTC, itzcoatl90 commented on app/src/main/res/layout/activity_update_password.xml
> +
Please remove empty lines of code for making your PR clean

2018-07-21 20:27 UTC, itzcoatl90 requested changes
Sorry, branch keep braking the app

2018-07-21 20:27 UTC, itzcoatl90 commented
<img width="1100" alt="screen shot 2018-07-21 at 4 26 34 pm" src="https://user-images.githubusercontent.com/2761835/43039816-e8b7e37a-8d02-11e8-93d7-4541215b3fc9.png">

2018-07-24 15:42 UTC, itzcoatl90 commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
This file should not be in PR

2018-07-24 15:42 UTC, itzcoatl90 commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
This file should not be in PR

2018-07-24 15:45 UTC, itzcoatl90 submitted a review, later dismissed
please

2018-07-24 20:34 UTC, ecejmsr approved these changes
Everything looks fine.

2018-07-24 20:35 UTC, merged