Created xml for recommended users fragment.
carlosjuarez/FinalProject pull request #29
Opened 2018-07-23 23:46 UTC by OnlyAlf

2018-07-24 16:22 UTC, itzcoatl90 commented on .idea/codeStyles/Project.xml
> +<component name="ProjectCodeStyleConfiguration">
no

2018-07-24 16:22 UTC, itzcoatl90 submitted a review, later dismissed
You know about the files

2018-07-24 21:03 UTC, ecejmsr requested changes

2018-07-24 21:03 UTC, ecejmsr commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
Hello blank fragment needs removal

2018-07-25 00:02 UTC, ecejmsr approved these changes
Looks good.

2018-07-25 00:02 UTC, merged